Feature/enum usuarios
vinnilmg/car-cheap-tc-fase-1 pull request #2
Opened 2024-05-16 01:18 UTC by gabrielflobao

Criado enum para perfils de usuarios

2024-05-20 22:06 UTC, vinnilmg commented on src/main/java/com/fiap/carcheap/enums/UserPerfils.java
> +    ADMINISTRATIVO,
Não existe esse perfil

2024-05-21 01:17 UTC, gabrielflobao commented on src/main/java/com/fiap/carcheap/enums/UserPerfils.java
> +    ADMINISTRATIVO,
Resolvido, Meu nobre

2024-05-21 03:05 UTC, amandsmir approved these changes

2024-05-21 21:37 UTC, vinnilmg requested changes

2024-05-21 21:37 UTC, vinnilmg commented on src/main/java/com/fiap/carcheap/enums/UserPerfis.java
> +    ADMINISTRATIVO,
Segundo nossa documentação, teremos o perfil MASTER e VENDEDOR.
Aqui seria o MASTER, o administrativo seria o tipo do usuário que teria esse perfil.

2024-05-22 12:32 UTC, gabrielflobao commented on src/main/java/com/fiap/carcheap/enums/UserPerfis.java
> +    ADMINISTRATIVO,
Deixando apenas o master e o vendededor.

2024-05-22 23:01 UTC, vinnilmg approved these changes

2024-05-22 23:01 UTC, merged